// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 5.2
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_photo(s,m,c){var h=jQuery,l=h("ul",c),c=c.parent(),j=m.length,p=s.imagesCount||30,n=30,o=80;var r=h("<div>").css({position:"absolute",top:0,left:0,width:"100%",height:"100%",overflow:"hidden",backgroundColor:"#DDDDDD"}).appendTo(c);var q=h("<div>").css({position:"absolute",top:0,left:0,width:"100%",height:"100%",backgroundColor:"rgba(0,0,0,0.6)",zIndex:4}).appendTo(r);var e=Math.max(p,m.length);for(var g=0,f=0;g<e;g++){if(f>m.length){f-=m.length}h(m[f]).clone().addClass("ws_photoItem").appendTo(r);f++}var a=r.children("img");h.support.transition=(function(){var i=document.body||document.documentElement,k=i.style;return k.transition!==undefined||k.WebkitTransition!==undefined||k.MozTransition!==undefined||k.MsTransition!==undefined||k.OTransition!==undefined})();function b(k,i){return parseFloat(Math.random()*(i-k)+k)}function d(B,v,i,u,k){if(u&&v){var C=o,A=50-C/2,z=50-C/2,t=0,w=5}else{var C=n,A=b(-10,90),z=b(-10,90),t=b(-30,30),w=v?5:(i?3:2)}B.css({position:"absolute",zIndex:w});if(h.support.transition){B.css({top:z+"%",left:A+"%",width:C+"%",height:C+"%",transform:"rotate("+t+"deg)",transition:"all "+k+"ms ease-in-out"})}else{B.animate({top:z+"%",left:A+"%",width:C+"%",height:C+"%"},k)}}a.each(function(i){d(h(this),s.startSlide==i,false,true,0)});this.go=function(i,t){if(window.XMLHttpRequest){var k=s.duration*0.5;a.each(function(u){d(h(this),i==u,t==u,false,k)});if(h.support.transition){q.css({opacity:0,transition:"all "+k*0.7+"ms ease-in-out"})}else{q.fadeOut(k*0.7)}setTimeout(function(){a.each(function(u){d(h(this),i==u,t==u,true,k)});if(h.support.transition){q.css("opacity",1)}else{q.fadeIn(k*0.7)}},k)}else{l.stop(true).animate({left:(i?-i+"00%":(/Safari/.test(navigator.userAgent)?"0%":0))},s.duration,"easeInOutExpo")}return i}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 5.2
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"photo",prev:"",next:"",duration:20*100,delay:20*100,width:830,height:360,autoPlay:true,playPause:true,stopOnHover:false,loop:false,bullets:0,caption:true,captionEffect:"move",controls:true,onBeforeStep:0,images:0});